### ISSUE TITLE
Learning block: Removing directory using command rm -i and rm -f

### ISSUE THREAD

**Issue by telads** [makersacademy/common-knowledge#237]
**Describe the situation**
I am unable to replicate the situation where I can use the command rm -i and rm -f 

**To Reproduce**
As I'm using AWS I wasn't able to replicate this command in the AWS environment. 

**Expected behaviour**
I was expected a prompt when using rm -i or remove the file when using rm -f

**Screenshots**

**Additional context**
Add any other context about the problem here

**Comment by dearshrewdwit** [comment]
A quick recap of the short pairing session we did:

We used `rm --help` to read the docs on how to use the command. We found out two things
1. -i is a valid option to use with the command
2. the usage is as follows: `rm [OPTION] FILE` where the option is optional

Compared with the usage we had tried, we realised we need to pass in a file as an argument to reach our expected behaviour
