### ISSUE TITLE
using the command grep and using pipes 

### ISSUE THREAD

**Issue by telads** [makersacademy/common-knowledge#243]
Attempting step 6 in the murder mystery challenge and I need to include `Height: 6'`as an additional input however the terminal does not recognise the character `'`. Additionally, if I include input within a string, the terminal wants me to add additional information...

**To Reproduce**
`student@Engineerings-MacBook-Air-Mid-2019 mystery % grep -A 6 L337 vehicles | grep -C 3 Blue | grep -C 4 Honda | grep -C 4 6'`
pipe pipe pipe quote>                                                                             
`grep -A 6 L337 vehicles | grep -C 3 Blue | grep -C 4 Honda | grep -C 4 "Height: 6"`
pipe pipe pipe quote> Height: 6
`grep -A 6 L337 vehicles | grep -C 3 Blue | grep -C 4 Honda | grep -C 4 'Height: 6'`
pipe pipe pipe quote> 

**Expected behaviour**
I am expecting to use the grep inputs to include certain lines of text using the combination of grep inputs I have used above

**Screenshots**
<img width="1440" alt="Screenshot 2020-07-24 at 12 10 54" src="https://user-images.githubusercontent.com/66533748/88385725-cb761480-cda6-11ea-8af9-7e7d2af27f3f.png">

**Additional context**

**Comment by dearshrewdwit** [comment]
Nice question @telads . What have you researched so far?

**Comment by telads** [comment]
Researched how to include a space character although I don't think that is the issue. When I want grep to search just for height, the output is
`pipe pipe pipe quote>`

**Comment by dearshrewdwit** [comment]
I see. What do you think is the issue then? How would you frame this problem as a question to google?

**Comment by elsstrange** [comment]
I did a bit of thinking about this one.  It's really hard to google - there's are far too many hits about grep, and searching on the mysterious `pipe pipe pipe quote>` line isn't very illuminating either.

I tried @telads 's command in my terminal and it runs fine.  But I was suspicious about the `quote>` part of what telads was getting back. The way it referenced "quote" and seemed to be prompting for more input reminded me of when I forget to close my message string off during a git commit command.

I found I could replicate what telads got back if I left the final double quote off the end of the command.
At the prompt, I can enter the closing quote, and the command then runs.

`grep -A 6 L337 vehicles | grep -C 3 Blue | grep -C 4 Honda | grep -C 4 "Height: 6`
`pipe pipe pipe quote>"`

But I'm very confused about why telads would be seeing the `pipe pipe pipe quote>` at all, since the commands shown in the original post do appear to include closing quotes.

**Comment by dearshrewdwit** [comment]
This is great! A clue is in the `quote>` part of the output. This happens as you've both noticed for an unclosed quote. The original command grepping for 6' caused this to happen - bash read it as the begining of a quote, not as a character to include in the search string for grep.

The tricky part looks like the quote was never closed even with the subsequent commands - the original quote was still open so every time valid commands were entered on the command line, it was within the unclosed quote. This might explain your confusion @telads @elsstrange 

In these situations hit `^c` a bunch until you see the normal prompt on the command line and then start again, or, you can just close the quote if you are aware of what the execution context is.

**Comment by dearshrewdwit** [comment]
On a separate note, @telads your questions are submitted with useful information with screenshots. Nice job, makes it easier to understand!

**Comment by telads** [comment]
Thank you, both! @elsstrange @dearshrewdwit 
Yes, I didn't try the speech marks around 6' > `student@Engineerings-MacBook-Air-Mid-2019 mystery % grep -A 6 L337 vehicles | grep -C 3 Blue | grep -C 4 Honda | grep -C 4 "6'"` as this has worked! I'll close the issue now. Thanks again!
